[phases.setup]
nixPkgs = ["nodejs_20", "openssl"]

[phases.install]
cmds = [
  "npm install --prefix client",
  "npm install --prefix server"
]

[phases.build]
cmds = [
  "npm run build --prefix client",
  "npx prisma generate --schema=server/prisma/schema.prisma"
]

[start]
cmd = "cd server && npm start"
